name: docker
on: pull_request
jobs:
  docker:
    name: Docker
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build docker image
        run: docker build --tag wrangler_reproduction .
      - name: Run docker
        run: docker run --name wrangler wrangler_reproduction &
      - name: Wait for wrangler to be up
        run: sleep 20s
      - name: Run shell on the docker image
        run: docker exec -it wrangler curl -v http://localhost:3000/index.html      
